version: '3.1'
 
services:
  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: itstep
  
  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8082:8080

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     depends_on: 
       - db
     ports:
       - 8081:80
     environment:
       MYSQL_ROOT_PASSWORD: itstep       
     restart: always

  zno:
    depends_on:
      - db
    image: itstepdev/zno
    build:
      context: .
    ports:
      - "8080:80"

volumes:
  dbdata:
    driver: local
